### ISSUE TITLE
Is there any way of making the rofi search case-insensitive?

### ISSUE THREAD

**Issue by edu-flores** [cdown/clipmenu#242]
Can't seem to find any information about this.

**Comment by edu-flores** [comment]
Found a solution:

1. Make a custom rofi configuration for clipmenu (e.g., `CM_LAUNCHER=rofi clipmenu -config ~/.config/rofi/clipboard.rasi`).
2. Add the `case-indicator` element to the configuration.
```css
/* Example */

inputbar {
    children: [ entry, case-indicator ];
    padding: 15 20;
}
```
3. Toggle case sensitiveness with the `kb-toggle-case-sensitivity` keybind (typically the backtick key).
